### ISSUE TITLE
Too many features are not working

### ISSUE THREAD

**Issue by ice1000** [Saigut/intellij-scheme#2]
Like file creations (no "create scheme file" in the right-click menu), completions (even I type `(de` and press <kbd>Ctrl</kbd>+<kbd>Space</kbd>), formatter (nothing happen when I invoke the formatting action), while I saw all those features appear in the source code.

**Comment by Saigut** [comment]
This plugin is modified from [cmf/schemely](https://github.com/cmf/schemely) which code is somehow too old to compiled on newer IntelliJ platforms.  
I made the old code can be compiled on newer IntelliJ platforms, and modified some code of the Lexer and Parser, and also with other modifcations.  
But this plugin is not well tested yet, and also have some issues that may be hard to be fixed for me. And I have little free time to work on this plugin recently.

**Comment by ice1000** [comment]
I know, and do you know that the parser and the lexer are generated? You shouldn't maintain generated code yourself.

**Comment by ice1000** [comment]
Oh my god, sorry, it's not..

**Comment by ttys3** [comment]
@ice1000 I got a build and only keep the syntax hightlight feature if this is what you need

https://github.com/ttys3/intellij-scheme/releases/tag/v0.1.7

**Comment by Saigut** [comment]
@ttys3 Good job!
