### ISSUE TITLE
Is there any chance get this plugin running on Rider IDE?

### ISSUE THREAD

**Issue by davidvontamar** [Saigut/intellij-scheme#3]
I'm a huge fan of JetBrain's new IDE for .NET.
Is there any chance getting this plugin running on Rider?

**Comment by Saigut** [comment]
Many IDE from JetBrain is based on IntelliJ platform. This plugin could run on Rider if it is also based on IntelliJ platform. 

And I searched on JetBrain plugin web page, it show this plugin can be installed on Rider: 
[https://plugins.jetbrains.com/search?correctionAllowed=true&pr=rider&orderBy=relevance&search=Scheme](https://plugins.jetbrains.com/search?correctionAllowed=true&pr=rider&orderBy=relevance&search=Scheme)

**Comment by davidvontamar** [comment]
I tried to, and I'm eager to start programming in Scheme using Rider.
It simply opts the plugin in gray and you can't even start a scheme project at all.
IntelliJ is too Java-centered for me, and I insist on working with Rider because I'm very familiar with C# and .NET.
Thanks for the reply btw.
________________________________

**Comment by ice1000** [comment]
@vontamar Rider is much more different from IntelliJ IDEA rather than PyCharm, RubyMine, etc.
Maybe I'll help improve this project when I've finished the basic features of the Zig and the Julia plugin.

**Comment by ice1000** [comment]
@Saigut 不行的，你看看CLion，创建项目的界面是没法插新选项进去的（到2018.1才开放，Kotlin Native插件是搞了黑科技才加进去的，所以闭源了）和Rider，直接钦点了sln，肯定没法用传统方式 new proj啊。

一般这种情况是在欢迎界面加按钮。我有空了给你发pr，不过记得去plugin repo把我设为contributor哦。

**Comment by Saigut** [comment]
@ice1000 OK

And I'll try Rider

**Comment by Saigut** [comment]
@vontamar  @ice1000  I've tried, and this plugin seems working normally as same as on Idea Community Edition and Clion. The highlighting is working, and the setting page like Code Style and Color Scheme is right there.
@vontamar  Maybe you should associate your file type with Scheme plugin?

![pic1](https://user-images.githubusercontent.com/2455241/37916926-af744734-314f-11e8-80f4-329ef9956378.png)
![pic2](https://user-images.githubusercontent.com/2455241/37916935-b5e4204e-314f-11e8-9b23-35d68791a8f8.jpg)
![pic3](https://user-images.githubusercontent.com/2455241/37916943-bb359fbe-314f-11e8-8771-689c7b975f8a.jpg)

@ice1000 And pull request for improvement is very welcome.

**Comment by davidvontamar** [comment]
It seems I've managed to get the syntax highlighting working, scheme files are indeed associated with Rider now, I can use the REPL too.
However the Solution Explorer seems to be totally broken, an empty solution shows up without any files in it.
I never actually used Scheme before, but as I type, I get no suggestions for functions like "display" and what their arguments.
I also seem to struggle to figure out how to run the Scheme code and get a console window to appear and show some output.
________________________________

**Comment by Saigut** [comment]
Hi, 
Highlighting should working without many issue, while other features are not well tested and maintained.

**Comment by ice1000** [comment]
This is too bad... I want start my own plugin now.

**Comment by ice1000** [comment]
```xml
	<id>intellij-scheme</id>
	<vendor url="https://saigut.com">Tony Saigut</vendor>

		<errorHandler implementation="com.intellij.diagnostic.ITNReporter"/>
```

**Comment by ice1000** [comment]
Why your `id` isn't a valid package name..

**Comment by ice1000** [comment]
Well I give up. This code is too legacy to be maintained. I've just fixed some warnings and errors, will open a pr later.

**Comment by Saigut** [comment]
This plugin can run on Rider IDE, so I close this issue.
